[package]
name = "grim_formats"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
memmap2 = "0.9"
clap = { version = "4", features = ["derive"] }
walkdir = "2"

[dev-dependencies]
tempfile = "3"
