[package]
name = "grim_stream"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
bytes = "1"
rmp-serde = "1"
serde = { version = "1", features = ["derive"] }
serde_repr = "0.1"
serde_bytes = "0.11"
serde_json = "1"
thiserror = "1"
