[package]
name = "grim_analysis"
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-or-later"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
full_moon = "0.18"
